### ISSUE TITLE
Frontend container not working

### ISSUE THREAD

**Issue by janisverins** [scandipwa/scandipwa-base#105]
**Describe the bug**
When setting up new scandipwa project with docker following the docs.scandipwa.com docs, frontend container is not working and no changes are being shown in frontend, only after restarting containers.

**My fix**
Adjusted docker-compose.frontend.yml file to this, restarted nginx and varnish and it is working now:

version: '3.6'
services:
  nginx:
    volumes:
      - ./deploy/frontend/conf/nginx/cache-router.conf:/etc/nginx/conf.d/cache-router.conf
    links:
      - frontend
  frontend:
    image: scandipwa/frontend:latest
    build:
      context: build/frontend
      args:
        - NODEJS_VERSION=${NODEJS_VERSION}
    volumes:
      - ./src/app/design/frontend/Scandiweb/pwa:/var/www/public/app/design/frontend/Scandiweb/pwa
      - ./src/vendor/scandipwa/source:/var/www/public/vendor/scandipwa/source
      - ./src/app/code:/var/www/public/app/code
      - ./src:/var/www/public
      # Uncomment line below only for testing launch script without rebuild
      # - ./build/frontend/start.sh:/start.sh
    env_file: .env
    working_dir: "/var/www/public/app/design/frontend/Scandiweb/pwa/"
    command: ["npm", "run", "pm2-watch"]
    expose:
      - 3003
  app:
    command: /wait-for-it.sh mysql:3306 -- /start.sh -F

**Comment by alfredsgenkins** [comment]
Closing for lack of context. I assume the `Scandiweb/pwa` is different on your project?
