### ISSUE TITLE
Product attributes with 'Used in Product Listing' set to 'Yes' are not present on the PLP

### ISSUE THREAD

**Issue by joostm020** [scandipwa/scandipwa-base#111]
**Definitions**
PLP = Product List Page (category page)
PDP = Product Detail Page (product page)

[Magento docs I used.](https://docs.magento.com/user-guide/stores/attributes-product.html#storefront-properties)

**Describe the bug**
Product attributes with **Used in Product Listing** set to **Yes** are not present in the GraphQL response on the PLP.

**To Reproduce**
1. Go to Stores -> Attributes -> Product -> Add new attribute
2. Fill in Default Label as 'Promo Label'
3. Fill in Attribute Code as 'promo_label'
4. Set **Visible on Catalog Pages on Storefront** as **No**
5. Set **Used in Product Listing** as **Yes**
6. Save the attribute
7. Re-index and flush cache

**Expected behavior**
The product attribute 'promo_label' should be:
- Present in GraphQL response and visible on the PLP (like in screenshot 1)
- Not visible on the PDP

**Observation**
When I changed **Visible on Catalog Pages on Storefront** to **Yes** the Promo Label is now displayed on the PLP and PDP, but this setting should only affect the PDP.
The screenshot below represent this observation.

**Screenshots**
_Screenshot 1_
![image](https://user-images.githubusercontent.com/26708268/89507089-548c4300-d7cc-11ea-8e9a-411dc859361f.png)

_Screenshot 2_
![image](https://user-images.githubusercontent.com/26708268/89507466-d67c6c00-d7cc-11ea-9e11-ab4a16721140.png)

**Comment by alfredsgenkins** [comment]
Implemented, see details here:
- https://github.com/scandipwa/performance/releases/tag/1.1.0
- https://github.com/scandipwa/catalog-graphql/releases/tag/2.15.1
- Upcoming 2.x and 3.x versions

**Comment by alfredsgenkins** [comment]
I will also migrate the issue to another repo.
