### ISSUE TITLE
unified interface for plugins

### ISSUE THREAD

**Issue by ahmadnwira** [scandipwa/scandipwa-base#112]
when working with plugins I found that the arguments type & arguments order is different between member-functions, member-property

for member-functions
arg1 is an array
arg2 is callback
arg3 is a proxy object

for member-properties
arg1 is a callback 
arg2 is a proxy object

I think all plugins should have the same interface.
*the docs are outdated so I couldn't figure what should array argument passed to member-function should represent but I see it's always empty!

**Comment by alfredsgenkins** [comment]
Moved to different repo
