### ISSUE TITLE
Project bootstrap optimization

### ISSUE THREAD

**Issue by Danpiel** [scandipwa/scandipwa-base#14]
To make onboarding simple and straightforward as possible, the following things must be done/improved:

- [x] Works by default with ssl container, check if certs are in place before execution.
- [ ] Database dump applied via wrapper script
- [ ] Media added via wrapper script
- [ ] Additional `make bootstrap` is added for project creation from scratch
- [x] Make `composer.json` out of repository to be able upgrade base code base without conflicts
- [x] xdebug config is attachable via mount, not bundled inside

**Comment by Danpiel** [comment]
@eli-l @alfredsgenkins any comments or additions, might forgot something important.

**Comment by alfredsgenkins** [comment]
By default the `env.php` is not appended with [persisted query](https://github.com/scandipwa/persisted-query#config) may we do this automatic?

**Comment by Danpiel** [comment]
composer.json are now mergeable and some hacks are removed, thanks to the https://github.com/scandipwa/slider/commit/38f15409cd03f6668e57d66b4b07a19f529f0ee8

**Comment by alfredsgenkins** [comment]
This issue is not a part of Milestone. It represents `Deploy for new env and struct`. @eli-l

**Comment by alfredsgenkins** [comment]
CLI will be introduced to automate all actions needed for project installation.
