### ISSUE TITLE
Homepage is blank

### ISSUE THREAD

**Issue by aleksejtsebinoga** [scandipwa/scandipwa-base#33]
**Describe the bug**
The page is blank sometimes.
Most likely, it happens when the page is opened for the first time during the day.

First was noticed when new styles were deployed.

**To Reproduce**
No steps to reproduce.
The issue happens randomly.

**Expected behavior**
The page should never be blank.

**Screenshots**
Desktop - https://prnt.sc/o3unnm
Mobile    - https://prnt.sc/o3urj0

**Desktop (please complete the following information):**
-   OS: Mac OS 10.14.5
-   Browser Chrome
-   Version 74.0.3729.169

**Smartphone (please complete the following information):**
-   Device: Samsung Galaxy S10+
-   OS: Android 9
-   Browser Chrome
-   Version 75.0.3770.89

**Comment by alfredsgenkins** [comment]
This probably more relates to `base-theme` not the `scandipwa-base`. Moved to https://github.com/scandipwa/base-theme/issues/189/

**Comment by eli-l** [comment]
_Most likely, it happens when the page is opened for the first time during the day._
It happens when service worker gets updated.
