### ISSUE TITLE
Theme is not displaying in the BE of Magento

### ISSUE THREAD

**Issue by aleksejtsebinoga** [scandipwa/scandipwa-base#34]
**Describe the bug**
It is impossible to switch a theme from the backend.
The ScandiPWA or any other bootstrapped theme is not present in none of -

Content -> Configuration
Content -> Theme

**To Reproduce**
1. Go to Admin;
2. Content -> Configuration;
3. Select Default Store View configs, by clicking on Edit;
4. In the dropdown of themes in the Default Themes section, no ScandiPWA or any other PWA bootstrapped theme.

**Expected behavior**
To be able to switch the theme from the backend

**Screenshots**
https://prnt.sc/o3wkz1

**Desktop (please complete the following information):**
- It is not important, as it is an M2 internal thing with registration the theme.

**Comment by alfredsgenkins** [comment]
Is fixed in https://github.com/scandipwa/installer/issues/5 fix pending in next release.

**Comment by alfredsgenkins** [comment]
I can recommend updating `scandipwa/installer` to 1.3.2. We will release this version as a part of `scandipwa-base` soon.
