### ISSUE TITLE
Magento 2 automatical bootstrap is failing with latest.sql applied

### ISSUE THREAD

**Issue by eli-l** [scandipwa/scandipwa-base#4]
**Describe the bug**

**To Reproduce**
1. Run `docker-compose  up -d`
2. Import `latest.sql`
3. Run `docker-compose  up -d --force-recreate`

**Expected behavior**
Magento 2 installs/updates without the errors automatically.

**Comment by alfredsgenkins** [comment]
Seems like Varnish is setup on incorrect port @eli-l . Is this issue related?

**Comment by Danpiel** [comment]
Varnish port was fixed by commit https://github.com/scandipwa/scandipwa-base/commit/a08b75829c53175326bd69fa96676575ae481d3d
