### ISSUE TITLE
How can we install SSL for ubuntu 18.04

### ISSUE THREAD

**Issue by jigneshmca1985** [scandipwa/scandipwa-base#45]
I have followed all steps but I got stuck at SSL installation. If you can guide us to install SSL on ubuntu 18.04 on the localhost set up so I can continue with scandi web PWA theme installation with the rest of the steps.

**Comment by Danpiel** [comment]
Hello, issue `make cert` command, it will pull another container and generate certificates. It will prompt for password input three times, use same password.

Once it finished, import CA certificate from opt/ssl/scandipwa-ca.pem into browser to make connections valid.

**Comment by jigneshmca1985** [comment]
@Danpiel Thank you for helping me with the SSL installation. 

Now, I am getting this error while running this command.

docker-compose -f docker-compose.yml -f docker-compose.local.yml -f docker-compose.ssl.yml up -d

Error 

ERROR: for scandipwabase_ssl-term_1  Cannot start service ssl-term: driver failed programming external connectivity on endpoint scandipwabase_ssl-term_1 (f9bc90d71cded73035796db3bb168c4dde75ac261c4e1404872b7343aca0f50f): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use

ERROR: for ssl-term  Cannot start service ssl-term: driver failed programming external connectivity on endpoint scandipwabase_ssl-term_1 (f9bc90d71cded73035796db3bb168c4dde75ac261c4e1404872b7343aca0f50f): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use
ERROR: Encountered errors while bringing up the project.

If you can take a look and provide any suggestions to fix this error that will help a lot to move ahead.

Thanks

**Comment by alfredsgenkins** [comment]
You have clearly something else running on the 443 port. Make sure to kill all the processes which do that. I recommend disabling local servers when doing this. If you have multiple instances of the project, make sure they are down before starting the new one.

Google how to kill the service on port. And, this is not the ScandiPWA issue. So please, Google before-hand :)
