### ISSUE TITLE
Media assets archive is outdated

### ISSUE THREAD

**Issue by boobooking** [scandipwa/scandipwa-base#50]
**Describe the bug**
The media assets archive (for those who install ScandiPWA demo) is outdated. Folder structure has changed:
1) there shouldn't be a media folder inside archive cause we extract archive into existing media folder.
2) there should be webp and svg folders, and catalog folder should be inside these folders.
3) Some products from last deploy/latest.sql don't have pictures in the archive.
etc.

Please update media archive with current changes.

**Comment by alfredsgenkins** [comment]
Which archive did you downloaded? The `2.2.x-media` has no `svg`, `webp` folders. Can you please download media referenced in `README.md` of `2.2.x` version? https://scandipwa-public-assets.s3-eu-west-1.amazonaws.com/2.2.x-media.tar.gz

**Comment by alfredsgenkins** [comment]
Why should we have `svg` and `webp` image folders? Those are absolete since `2.0^`

**Comment by alfredsgenkins** [comment]
Please use matching theme version and base version. We can only ensure correct behavior for `1.x` of theme to base compatibility, and `2.x` of base to theme :)

**Comment by boobooking** [comment]
I don't know how to match theme and base. I just followed the README installation procedure.
And checked in nginx and varnish logs that urls with */webp/* and */svg/* are still requested.

I had to move folders in archive into webp and svg to get theme partly working. By default after extracting archive as described in README results in 404 for every asset.

**Comment by alfredsgenkins** [comment]
If your theme looks like this https://demo.scandipwa.com/ this is V2. If like this: https://v1.scandipwa.com/ then this is V1. I can not validate a claim related to `svg`, `webp` requests, there are none for me.

**Comment by alfredsgenkins** [comment]
Please see default branch. We are not using `master`. Your go-to is `2.x-stable`.

**Comment by boobooking** [comment]
Yeah, the problem was with incorrect branch. The result I've got is v1 theme version from master branch.
