### ISSUE TITLE
Custom urls of my modules always return 404 with ScandiPWA theme

### ISSUE THREAD

**Issue by boobooking** [scandipwa/scandipwa-base#52]
Hi!

My magento module registers custom url (let's say /marketplace) in /etc/frontend/routes.xml
Everything works fine with default Magento theme.

But after switching to ScandiPWA theme every registered url returns 404 (styled with scandi).
If I switch back to default theme - everything is ok again.

What happens with other modules's urls after enabling ScandiPWA? Where to dig to solve it?

Thanks!

**Comment by alfredsgenkins** [comment]
Eventhought ScandiPWA is a theme, it using a completely separate routing system from Magento. You can still proxy the request directly to Magento, but for most frontend cases we use React router. It functions in ScandiPWA and respect only routes declared in theme - product, category & etc. Magento declared routes are not respected. This is not an issue either, as M2 routes are SSR and our app is CSR so it simply impossible to use same declarations.
