### ISSUE TITLE
There are no commands defined in the "config" namespace. 

### ISSUE THREAD

**Issue by livioweb** [scandipwa/scandipwa-base#53]
**Describe the bug**

I don't know if it's a bug, but I still can't install scandiaPWA, an error always comes up.

First it was permission in the src / folder, then it was with vanish
 how are the outputs copied there.
# Add user for MagentoDev application
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www
RUN gpasswd -a www root

**To Reproduce**

app_1            |   There are no commands defined in the "config" namespace.  
app_1            |                                                             
app_1            |   Did you mean one of these?                                
app_1            |       app:config                                            
app_1            |       module:config                                         
app_1            |       setup:config                                          
app_1            |       setup:store-config 

Error reaching Varnish: Unable to connect to varnish:80 . Error #0: stream_socket_client(): unable to connect to varnish:80 (php_network_getaddresses: getaddrinfo failed: Name or service not known)

**Comment by alfredsgenkins** [comment]
Closing, possibly fixed in newer releases.
