### ISSUE TITLE
Does anyone come across the same Magento application is not installed issues?

### ISSUE THREAD

**Issue by GoogleYY** [scandipwa/scandipwa-base#54]
Environment: Ubuntu 16.04 LTS
Docker and Docker Compose works well

My steps are below:

1.git clone https://github.com/scandipwa/scandipwa-base.git

2.cd scandipwa-base

3. run export COMPOSER_AUTH='{"http-basic":{"repo.magento.com": {"username": "REPLACE_THIS", "password": "REPLACE_THIS"}}}'  the user name and password is my public key and private key respectively obtained from Magento Marketplace.

4. make cert

5. docker-compose -f docker-compose.yml -f docker-compose.local.yml -f docker-compose.ssl.yml pull

6. docker-compose -f docker-compose.yml -f docker-compose.local.yml -f docker-compose.ssl.yml up -d

7. docker-compose -f docker-compose.yml -f docker-compose.local.yml -f docker-compose.ssl.yml logs -f app

in step 7, I got the errors as shown in the screenshot:

![result](https://user-images.githubusercontent.com/18476328/72325278-b9286900-36e7-11ea-9c4d-16e5b2bf61c9.png)

Very appreciated if anyone can give me a guide. Thank you

**Comment by alfredsgenkins** [comment]
Thanks. I am unavailable at the moment, while this issue looks high priority, from first glance @GoogleYY did everything correctly. @eli-l could you please take look?

**Comment by aliarsalan177** [comment]
I'm facing the same issue from yesterday it was working in before.
scandipwa-base_app_1             /usr/local/bin/entrypoint. ...   Exit 1                                        
scandipwa-base_elasticsearch_1   /bin/bash bin/es-docker          Up           0.0.0.0:9200->9200/tcp, 9300/tcp 
scandipwa-base_maildev_1         bin/maildev bin/maildev -- ...   Up           25/tcp, 0.0.0.0:1080->80/tcp     
scandipwa-base_mysql_1           docker-entrypoint.sh mysqld      Up           0.0.0.0:3307->3306/tcp, 33060/tcp
scandipwa-base_nginx_1           nginx -g daemon off;             Up           0.0.0.0:3031->80/tcp, 8090/tcp   
scandipwa-base_redis_1           docker-entrypoint.sh redis ...   Up           0.0.0.0:6379->6379/tcp           
scandipwa-base_rendertron_1      docker-entrypoint.sh npm r ...   Up           8083/tcp                         
scandipwa-base_varnish_1         varnish-entrypoint               Restarting      

varnish state to restarting when start app

**Comment by gohoney** [comment]
I'm facing the same issue and have tried so many times
my vps is ubuntu18.04 with installed docker docker-compose
app_1            | No upgrade/install is needed
app_1            | Setting redis as config cache
app_1            | We saved default values for these options: amqp-host, amqp-port, amqp-user, amqp-password, amqp-virtualhost, amqp-ssl, amqp-ssl-options.
app_1            | Setting redis as session storage
app_1            | We saved default values for these options: amqp-host, amqp-port, amqp-user, amqp-password, amqp-virtualhost, amqp-ssl, amqp-ssl-options.
app_1            | Setting Elasticsearch5 as a search engine
app_1            | 
app_1            |                                                             
app_1            |   There are no commands defined in the "config" namespace.  
app_1            |                                                             
app_1            |   Did you mean one of these?                                
app_1            |       app:config                                            
app_1            |       module:config                                         
app_1            |       setup:config                                          
app_1            |       setup:store-config                                    
app_1            |                                                             
app_1            | 
app_1            | Setting elasticsearch as a host name for Elasticsearch5
app_1            | 
app_1            |                                                             
app_1            |   There are no commands defined in the "config" namespace.  
app_1            |                                                             
app_1            |   Did you mean one of these?                                
app_1            |       app:config                                            
app_1            |       module:config                                         
app_1            |       setup:config                                          
app_1            |       setup:store-config

**Comment by aliarsalan177** [comment]
Did you check 'docker-compose ps' ? 
varnish-entrypoint restarting ?

**Comment by alfredsgenkins** [comment]
What is your branch? Make sure it is 2.x-stable.

Otherwise, it is very strange behavior. @peterflex7 @gohoney have you successfully resolved this?

**Comment by alfredsgenkins** [comment]
I think FAQ https://docs.scandipwa.com/docs/installation/faq/ should help you!
