### ISSUE TITLE
Scandipwa-docker build varnish error library geoip2

### ISSUE THREAD

**Issue by iamdylanngo** [scandipwa/scandipwa-base#56]
**Describe the bug**
scandipwa-docker build varnish error lib geoip2

When I run the command: 
docker-compose -f docker-compose.yml -f docker-compose.local.yml -f docker-compose.ssl.yml up -d --force-recreate
docker-compose -f docker-compose.yml -f docker-compose.local.yml -f docker-compose.ssl.yml logs varnish

It shows error:
![Screenshot from 2020-01-31 10-13-32](https://user-images.githubusercontent.com/11944757/73509731-ba110880-4412-11ea-8dc2-e4d73ef8fad0.png)

How to fix it?

Thanks

**Comment by alfredsgenkins** [comment]
Make sure you pulled the latest changes in scandipwa-base got repository (`2.x-stable` branch). Then, make sure you pulled latest images `docker-compose -f docker-compose.yml -f ... pull`. An issue fixed a month ago.

**Comment by iamdylanngo** [comment]
I checkout in master branch, It not correct
