### ISSUE TITLE
Error go to home page

### ISSUE THREAD

**Issue by iamdylanngo** [scandipwa/scandipwa-base#57]
**Describe the bug**
When I checkout to 2.x-stable branch and deploy
I go to home page It throws the error
![Screenshot from 2020-02-03 18-16-24](https://user-images.githubusercontent.com/11944757/73649108-a1724e00-46b1-11ea-8710-9fc9dd3d538a.png)

Thanks

**Comment by alfredsgenkins** [comment]
Hey! It seems like a theme is not setup correctly. Have you compiled it? Can you find a Magento_Theme folder in your app/design/VENDOR/THEME?

**Comment by iamdylanngo** [comment]
Yes, Magento_Theme folder inside app/design/VENDOR/THEME. Think code in Magento_Theme is not correctly, When delete folder app/design/VENDOR/THEME and rebuild is worked.
Thanks
