### ISSUE TITLE
Error when docker start frontend environment

### ISSUE THREAD

**Issue by niteco-scandipwa** [scandipwa/scandipwa-base#59]
**Describe the bug**
When I run command: 
docker-compose -f docker-compose.yml -f docker-compose.ssl.yml -f docker-compose.frontend.yml up -d

docker-compose -f docker-compose.yml -f docker-compose.ssl.yml -f docker-compose.frontend.yml logs -f frontend

Response is:
![Screenshot from 2020-02-04 17-47-05](https://user-images.githubusercontent.com/60464706/73738261-c086e380-4776-11ea-8dbf-9e84a646bc02.png)

**Comment by alfredsgenkins** [comment]
Can you please see above for the reason of pm2 not being installed? :) I mean it is not installing it for a reason. Scroll up.

**Comment by niteco-scandipwa** [comment]
Scroll up here:
![Screenshot from 2020-02-05 09-54-23](https://user-images.githubusercontent.com/60464706/73806989-9593a280-47fd-11ea-9518-369df696a0be.png)

**Comment by alfredsgenkins** [comment]
Aha, yes!

I was out of context that we are speaking about frontend container :)

This can be solved easily, while first, please check the app container logs, why has not he comiled a theme? Are there any errors?

To resolve this issue, please do following: 
1. Go to application (`app`) container,
2. Go to `app/design/frontend/Scandiweb/pwa`.
3. Run `npm ci`
4. Exit,
5. Restart Frontend.

**Comment by niteco-scandipwa** [comment]
Thank you very much :D
