### ISSUE TITLE
Getting error while running the frontend container

### ISSUE THREAD

**Issue by aliarsalan177** [scandipwa/scandipwa-base#60]
I'm getting this while trying to run the sacndipwa in development mode with frontend container 

<img width="797" alt="Screen Shot 2020-02-05 at 1 41 58 PM" src="https://user-images.githubusercontent.com/26825774/73825249-74db4500-481d-11ea-8c35-b8088cb3796f.png">

**Comment by alfredsgenkins** [comment]
Did you ran `npm i`? Can you please run `npm ci` from Frontend container. Will it help?

**Comment by alfredsgenkins** [comment]
How to reproduce it? It is a common issue, but we never had a real step-by-step to reproduce it!

**Comment by aliarsalan177** [comment]
did I use this to connect to frontend container ? "docker-compose exec frontend bash -l"
I tried this but it's said no such service?
i have run npm ci from the theme directory but its doesn't work at all

**Comment by aliarsalan177** [comment]
docker-compose -f docker-compose.yml -f docker-compose.frontend.yml -f docker-compose.ssl.yml pull
run this first then docker-compose -f docker-compose.yml -f docker-compose.frontend.yml -f docker-compose.ssl.yml up -d 
 
then i log the frontend container its building but after that its always give the same error ?

**Comment by alfredsgenkins** [comment]
Yes, yes. Sorry, please use the `docker-compose exec -u user app bash -l` to get into to the `app`. I miss-spelled. Go to `/var/www/public/app/design/frontend/Scandiweb/pwa`, run `npm ci` and `npm run build` for now. The restart your stack with `docker-compose -f ... up -d`.

And also, please report your `node -v` from the app container. And `node -v` from frontend container (use the command `docker-compose exec frontend bash -l` to get inside). Make sure they are both 10.

**Comment by aliarsalan177** [comment]
I have tried everything but still frontend container creating issue :( @alfredsgenkins

**Comment by alfredsgenkins** [comment]
The same issue? Wow!
Let me address this issue and get back to you tommorow. For now, there is a fix from community:
```
 docker-compose exec -u root app bash
 n 10
 exit
 docker-compose exec -u user app bash
 cd app/design/frontend/Scandiweb/pwa
 npm ci
```

**Comment by alfredsgenkins** [comment]
I am sorry for long reply, notifications were not sending. Sorry!

**Comment by iamdylanngo** [comment]
I think you must go to container frontend and rebuild node-sass:
docker exec -ti <docker_frontend_id> bash
npm rebuild node-sass
:D

**Comment by alfredsgenkins** [comment]
@jundat95 no, this was not helping.

This issue has been resolved, we have updated  the NODE_JS version to 10 in the app container and in the Frontend.
