### ISSUE TITLE
When start docker it throw error

### ISSUE THREAD

**Issue by iamdylanngo** [scandipwa/scandipwa-base#61]
**Describe the bug**

When I run command:

docker-compose -f docker-compose.yml -f docker-compose.local.yml -f docker-compose.ssl.yml up -d --force-recreate

docker-compose -f docker-compose.yml -f docker-compose.local.yml -f docker-compose.ssl.yml logs -f app

It throw error:

![Screenshot from 2020-02-06 15-40-16](https://user-images.githubusercontent.com/11944757/73919958-200bfd00-48f7-11ea-818d-d3a42577d2f1.png)

Thanks

**Comment by alfredsgenkins** [comment]
How old is your setup? This should no longer be an issues, try pulling latest image of ScandiPWA. Use:

```bash
docker-compose -f docker-compose.yml -f docker-compose.local.yml -f docker-compose.ssl.yml pull
```

**Comment by iamdylanngo** [comment]
Thank you.
