### ISSUE TITLE
Error fetching header or footer & error fetching catalog 

### ISSUE THREAD

**Issue by Rain921** [scandipwa/scandipwa-base#62]
**Describe the bug**
I used your installation guide from the video "Getting started - demo setup"
after running app_1
 content is not loaded and writes
there is such an inscription on the main page, for example, in the catalog, such as this, the browser does not have errors

**To Reproduce**

![изображение](https://user-images.githubusercontent.com/31802686/73956519-b9460e00-490d-11ea-98fe-ebd3230d40ae.png)
![изображение](https://user-images.githubusercontent.com/31802686/73956779-1a6de180-490e-11ea-9306-2474d4d3cd78.png)
![изображение](https://user-images.githubusercontent.com/31802686/73956813-26f23a00-490e-11ea-9368-1472f9afdb52.png)

**Desktop (please complete the following information):**
-   OS: linux(ubuntu)18.02

**Additional context**
how is it
Thanks

**Comment by alfredsgenkins** [comment]
Wow, sorry for late reply. Anything in the Magento logs? Very strange! How you installed a theme? Did you use dump?

**Comment by RolyMolnar** [comment]
This happened to me today. Please update the docs if something changed.

**Comment by redati** [comment]
I also had the same problem.
and the error 500 in / graphql

I noticed that it doesn't work well in 2.3.4.

The demo version has a scroll problem, the scroll does not appear on a small screen descktop.

**Comment by edvillareal26** [comment]
Hi, I have same situation where existing magento installation 2.3.3 with varnish. Installed the data via sampledata:deploy and install scandipwa theme bin/magento scandipwa:theme:bootstrap. Do I need to do something in the magento cms?

https://magento-385650-1212322.cloudwaysapps.com/

<img width="1440" alt="scandierror" src="https://user-images.githubusercontent.com/444977/77827161-0648a280-714f-11ea-96b4-6ad02e5b2fdd.png">

**Comment by alfredsgenkins** [comment]
`I noticed that it doesn't work well in 2.3.4.` - according to docs ScandiPWA does not support 2.3.4. Please re-open if reproducible on latest release.
