### ISSUE TITLE
Warning throw when use session_start() function

### ISSUE THREAD

**Issue by tinh-ngo-niteco** [scandipwa/scandipwa-base#70]
**Describe the bug**
Server throws a log in var/log/system.log

[2020-04-17 08:20:26] main.ERROR: Warning: session_start(): Failed to read session data: user (path: /var/www/public/var/session/) in /var/www/public/vendor/magento/framework/Session/SessionManager.php on line 208 [] []

**To Reproduce**

1. Go to the home page and another page

**Screenshots**
![Screenshot from 2020-04-17 15-25-17](https://user-images.githubusercontent.com/38058535/79548449-ae52eb00-80bf-11ea-8c7d-bd688abf5d0d.png)

**Desktop (please complete the following information):**
-   OS: Ubuntu 18.04 LTS
-   Browser: Chrome

**Comment by alfredsgenkins** [comment]
I think this is no longer the case at this point. Let me know if you are able to reproduce it tho!
