### ISSUE TITLE
Certificated trusted issue

### ISSUE THREAD

**Issue by Neelchudasama1** [scandipwa/scandipwa-base#77]
Hello,
I can create certificate successfully as per your instruction in document,
And  when i make it trusted using following command "trust anchor --store opt/cert/scandipwa-ca.pem" then it shows me "p11-kit: no configured writable location to store anchors"
Then i also apply it for manually as per documentation.
After that all the process got completed and try to open following url "https://scandipwa.local/" the it show me
![Screenshot from 2020-04-26 17-16-37](https://user-images.githubusercontent.com/25001427/80317692-e32f1280-8822-11ea-9a9b-d65d3e3a71d8.png)
![Screenshot from 2020-04-26 17-16-43](https://user-images.githubusercontent.com/25001427/80317694-e5916c80-8822-11ea-89bd-5cf857ed073d.png)

**Comment by alfredsgenkins** [comment]
I think it is covered here - https://docs.scandipwa.com/docs/installation/faq/#the-err_cert_revoked-in-chrome
