### ISSUE TITLE
Catalog URL 

### ISSUE THREAD

**Issue by onlinebizsoft** [scandipwa/scandipwa-base#79]
**Describe the bug**
Catalog URL are different from native Magento catalog URL

**To Reproduce**
1. Go to the demo or local setup
2. Visit any category or product page
3. Category URL start with /category/xxxx
Product URL start with /product/xxxxx

**Expected behavior**
Magento Catalog URL should stay same

**Additional context**
I'm not sure if this is a bug or it is expected behavior. If it is an expected behavior then why don't or we can't we keep all URL same as they are in a native Magento installation? It will be much better and easier for migrating from an existing website.

**Comment by alfredsgenkins** [comment]
Resolved in release 2.14.0 of scandipwa/source (https://github.com/scandipwa/base-theme)
