### ISSUE TITLE
Multi language website

### ISSUE THREAD

**Issue by ioanmeri** [scandipwa/scandipwa-base#82]
I would like to ask if having a **multi language website** with the ScandiPWA theme is currently supported.

I have managed to generate a translation bundle for each new locale (with npm run extract-translations) and have multiple stores with different languages. But I would like each store to have **the magento store code at the url**. E.g. scandipwa.local/en/promo and scandipwa.local/fr/promo and the same for categories, products, cms pages etc.. Is this functionality supported by scandiPWA?

Note: 
* I have followed all the necessary steps to create a multi language website in Magento Admin
* I am running scandipwa with docker production build (not development)

**Comment by alfredsgenkins** [comment]
ScandiPWA is not supporting URL based stores, yet. Working on it for 2.15.0
