### ISSUE TITLE
URL rewrite not working

### ISSUE THREAD

**Issue by santosh-gaggle** [scandipwa/scandipwa-base#96]
**Describe the bug**
Magento URL rewrites not working here

**To Reproduce**
1. Go to the category page or Product page
2. You will see the URL on category page like https://demo.scandipwa.com/category/xxxxxxxxxx
  OR
3. You will see the URL on Product  page like https://demo.scandipwa.com/product/xxxxxxxxxx

**Expected behavior**
It should be like  https://demo.scandipwa.com/xxxxxxxxxx

**Comment by alfredsgenkins** [comment]
Implemented in 2.14.0 of https://github.com/scandipwa/base-theme please update and try again. The /category and /product were removed from theme.
