### ISSUE TITLE
Sort By Brand In PLP

### ISSUE THREAD

**Issue by ankithg04** [scandipwa/scandipwa-base#99]
**Describe the bug**
sort by the brand in Product Listing Page i.e., Category is Redirecting to 404

**To Reproduce**
1. Go to Product Listing Page
2. Click on click on sort by dropdown
3. Select the sort by brand, and even attribute size.
4. Redirects to 404 page 

**Expected behavior**
As per the process, it should show the products sorted by brand name.

**Screenshots**
![screenshot-demo scandipwa com-2020 07 01-12_16_44](https://user-images.githubusercontent.com/45291590/86212202-38760000-bb95-11ea-8b85-62d5e65ba53b.png)

**Comment by alfredsgenkins** [comment]
Should be resolved in newest version of ScandiPWA. Please re-open in https://github.com/scandipwa/base-theme if issues is still reproducible again.
